// generated by tr2jag_multiroom.py - PSX TR1 LEVEL1 rooms [0, 7, 8, 15, 1, 2, 6, 9, 10, 16, 17, 18, 11, 12, 13, 3, 4, 5, 14]
#define MRT_ROOMCOUNT   19
#define MRT_ATLAS_W     256
#define MRT_ATLAS_H     908
// ramp palette: slot = base*RAMP_M + shade, 0=brightest;
// runtime shade pass adds k (0..RAMP_M-1) to the texel index
#define MRT_RAMP_K      30
#define MRT_RAMP_M      8
#define MRT_FACE_PLANES 1
#define MRT_LARA_IDX_BASE 242
#define MRT_LARA_N        4
#define MRT_LARA_CELL     8
#define MRT_LARA_SW_Y     884
// mrt.bin: u16 roomCount,atlasW,atlasH,pad; roomCount*{u32 geom_off,sect_off}
// mrt_geom/mrt_sect: concatenated room0_tex / room0_sect blobs (8-aligned)
// portal adjacency (local room indices; 255-padded)
#define MRT_ADJ_MAX 8
static const unsigned char mrt_adj[MRT_ROOMCOUNT][MRT_ADJ_MAX] = {
  {1,255,255,255,255,255,255,255}, // room 0 -> [1]
  {0,2,3,4,255,255,255,255}, // room 7 -> [0, 2, 3, 4]
  {1,5,6,7,255,255,255,255}, // room 8 -> [1, 5, 6, 7]
  {1,255,255,255,255,255,255,255}, // room 15 -> [1]
  {1,255,255,255,255,255,255,255}, // room 1 -> [1]
  {2,255,255,255,255,255,255,255}, // room 2 -> [2]
  {2,255,255,255,255,255,255,255}, // room 6 -> [2]
  {2,8,9,255,255,255,255,255}, // room 9 -> [2, 8, 9]
  {7,10,11,12,255,255,255,255}, // room 10 -> [7, 10, 11, 12]
  {7,255,255,255,255,255,255,255}, // room 16 -> [7]
  {8,255,255,255,255,255,255,255}, // room 17 -> [8]
  {8,255,255,255,255,255,255,255}, // room 18 -> [8]
  {8,13,255,255,255,255,255,255}, // room 11 -> [8, 13]
  {12,14,15,16,17,255,255,255}, // room 12 -> [12, 14, 15, 16, 17]
  {13,18,255,255,255,255,255,255}, // room 13 -> [13, 18]
  {13,255,255,255,255,255,255,255}, // room 3 -> [13]
  {13,255,255,255,255,255,255,255}, // room 4 -> [13]
  {13,255,255,255,255,255,255,255}, // room 5 -> [13]
  {14,255,255,255,255,255,255,255}, // room 14 -> [14]
};
