/* generated by tr2jag_title.py */
#define PASS_NPOSE 5
#define PASS_ATLAS_W 256
#define PASS_ATLAS_H 294
#define PASS_POSE0_OFF 0
#define PASS_POSE1_OFF 1840
#define PASS_POSE2_OFF 3680
#define PASS_POSE3_OFF 5520
#define PASS_POSE4_OFF 7360
