/* generated by tr2jag_title.py */
#define PASS_NPOSE 5
#define PASS_ATLAS_W 256
#define PASS_ATLAS_H 126
#define PASS_POSE0_OFF 0
#define PASS_POSE1_OFF 2264
#define PASS_POSE2_OFF 4528
#define PASS_POSE3_OFF 6792
#define PASS_POSE4_OFF 9056
