// generated by tr2jag_multiroom.py - PSX TR1 LEVEL1 Lara run cycle
// mrt_lara.bin (BIG-ENDIAN):
//   HEADER 12B: u16 vcount,qcount,tcount,framecount,atlasW,atlasH
//   QUADS  qcount*24: u16 v0,v1,v2,v3 ; u16 (u,v)x4  (v2<->v3 + uv2<->uv3 swapped)
//   TRIS   tcount*18: u16 v0,v1,v2   ; u16 (u,v)x3
//   FRAMES framecount*(vcount*6): s16 x,y,z  (Lara-local, +Y down, world units)
#define MRT_LARA_VCOUNT     300
#define MRT_LARA_QCOUNT     151
#define MRT_LARA_TCOUNT     274
#define MRT_LARA_FRAMECOUNT 66
#define MRT_LARA_FRAMESIZE  1800  // bytes per frame (vcount*6)
#define MRT_LARA_RUNFRAMES  22  // run cycle = frames 0..RUNFRAMES-1
#define MRT_LARA_STANDFRAME 22  // idle stand pose
#define MRT_LARA_JUMPSTART  23  // (compat) forward-jump first frame
#define MRT_LARA_JUMPFRAMES 7  // (compat) forward-jump length
#define MRT_LARA_FJUMPSTART  23  // FORWARD (running) jump first frame
#define MRT_LARA_FJUMPFRAMES 7  // forward-jump length
#define MRT_LARA_UJUMPSTART  30  // UP (standing/vertical) jump first frame
#define MRT_LARA_UJUMPFRAMES 5  // up-jump length
#define MRT_LARA_CLIMBSTART  35  // hang->pull-up (jump grab) first frame
#define MRT_LARA_CLIMBFRAMES 16  // hang->pull-up length
#define MRT_LARA_VAULT2START 51  // standing kick-flip vault (2 clicks)
#define MRT_LARA_VAULT2FRAMES 15
#define MRT_LARA_VAULT3START 51  // standing kick-flip vault (3 clicks)
#define MRT_LARA_VAULT3FRAMES 15

// ---- runtime skinning (mrt_lskin.bin, BIG-ENDIAN) ----
//   HEADER 16B: u16 mcount,vcount,qcount,tcount,animcount,framecount,framestride,pad
//   MESHINFO mcount*{u16 vbase,vlen}; MESHVERTS vcount*{s16 x,y,z}
//   NODES (mcount-1)*{u16 flags,s16 x,y,z}
//   FRAMES framecount*{s16 rootx,y,z; mcount*(u8 ax,ay,az)}  (angle idx 0..255)
//   ANIMS animcount*{u16 frameStart,frameCount; u8 state,rate}
#define MRT_LSKIN_MCOUNT     15
#define MRT_LSKIN_VCOUNT     300
#define MRT_LSKIN_ANIMCOUNT  160
#define MRT_LSKIN_FRAMECOUNT 2059
#define MRT_LSKIN_FRAMESTRIDE 52  // bytes/frame (padded even)
#define LANIM_WALK      1
#define LANIM_RUN       0
#define LANIM_STOP      11
#define LANIM_FJUMP     16
#define LANIM_FASTBACK  88
#define LANIM_TURNR     12
#define LANIM_TURNL     13
#define LANIM_DEATH     25
#define LANIM_FALL      22
#define LANIM_HANG      29
#define LANIM_REACH     94
#define LANIM_TREAD     107
#define LANIM_COMPRESS  73
#define LANIM_BACK      38
#define LANIM_HANGUP    26
#define LANIM_FASTTURN  44
#define LANIM_STEPR     67
#define LANIM_STEPL     65
#define LANIM_SLIDE     70
#define LANIM_BACKJUMP  74
#define LANIM_RIGHTJUMP 80
#define LANIM_LEFTJUMP  78
#define LANIM_UPJUMP    27
#define LANIM_FALLBACK  93
#define LANIM_SLIDEBACK 104
// TR1 footfall frames per animation (255 = none), from the
// anim SOUND commands with sound id 0. Offset within the cycle.
#define MRT_LARA_ANIMCOUNT 160
static const unsigned char mrt_lara_foot[160][2] = {
  {  4, 15}, {  4, 24}, {  4, 15}, {  4, 14}, {255,255}, {255,255}, { 10,255}, { 16,255},
  {  1,  9}, { 14,  0}, {  3, 12}, {255,255}, {  3, 17}, { 13, 27}, {255,255}, { 13, 19},
  {  1,255}, {255,255}, {  1,255}, {255,255}, {255,255}, {  6,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {  6,255}, {  5,255},
  { 12, 42}, {255,255}, { 45,255}, {255,255}, { 20,  9}, {255,255}, {255,255}, {255,255},
  {  5,255}, {255,255}, { 11,255}, {  7,255}, {255,255}, {255,255}, {255,255}, {  1,255},
  {  1,255}, {  2,255}, {  5,255}, {  7,255}, {  6,255}, { 12,255}, { 13,255}, {255,255},
  {255,255}, { 15, 24}, {255,255}, { 14, 24}, {255,255}, { 12, 20}, {255,255}, {  0,  6},
  {  8,255}, {  3,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, { 17,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, { 11,255}, {  3,255}, {255,255}, {  1,255}, {255,255}, {255,255}, {255,255},
  {255,255}, { 52, 69}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {  6, 13}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, { 22, 11},
  {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255}, {255,255},
};
#define LANIM_PICKUP    135
#define LANIM_HANDSTAND 159
#define LANIM_IDLE      103
#define LANIM_VAULT     50
#define LANIM_CLIMB3    42
#define LANIM_CLIMBJUMP 26
