#!/usr/bin/env python3
"""portal_open.py - open the WALL cells a room PORTAL passes through.

    tools/portal_open.py --prefix mrt            # report
    tools/portal_open.py --prefix mrt --patch    # rewrite <prefix>_sect.bin

WHY (run 71): the Caves were not walkable past room 0. **25 of 38 rooms had ZERO
0x7FFE openings**, and Lara physically stopped at z=21430 walking +Z out of room
0 while `g_floorroom` already read 1. The 0->1 portal is a plane at z=21504 and
both rooms tile across it with WALL on either side, so `room_wall_at` - which
tests the room she is IN - blocked her.

`tr2jag_multiroom.py:3191` only opens a cell when its SECTOR carries an FD portal
command (`func==1`) or is in `doorcells`. It never consults the room's PORTAL
LIST, which is the thing that actually describes a doorway. `project_room_
crossing_fixed` records the intended fix as "mark wall cells under a portal's XZ
footprint" - that is what this does.

☠️ THE FOOTPRINT IS ZERO-THICKNESS. A portal quad is a PLANE: for a z-portal
every corner shares one z. "Cells whose centre lies inside the quad" therefore
matches NOTHING, which is almost certainly why the original fix missed these.
The plane SEPARATES two cell rows, so open the row on each side of it.

☠️ Only 0x7FFF (solid) cells are touched. A real floor is never overwritten, and
0x7FFE cells are already open. That makes this idempotent and safe to re-run.

☠️ <prefix>_sect.bin is GITIGNORED and regenerated by the extractor, so this must
run from build_cof.sh after every regen or it evaporates - which is how the
2026-07-30 fix was lost.
"""
import os, re, struct, sys

def _disc(p):
    """Level-set files moved to disc/ (gitignored) on 2026-08-19. Prefer that,
    fall back to the old tree root so the tool works either side of the move."""
    import os as _o
    d = _o.path.join(_o.path.dirname(p), "disc", _o.path.basename(p))
    return d if _o.path.exists(d) else p

D = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CELL = 1024
WALL, OPEN = 0x7FFF, 0x7FFE


def portals(prefix):
    """(room, dst, xs, ys, zs) per portal, from <prefix>_spawn.h."""
    src = open(_disc(os.path.join(D, prefix + "_spawn.h"))).read()
    mo = re.search(prefix + r'_portal_ofs\s*\[[^\]]*\]\s*=\s*\{(.*?)\};', src, re.S)
    mp = re.search(prefix + r'_portalv\s*\[[^\]]*\]\s*\[[^\]]*\]\s*=\s*\{(.*?)\n\};', src, re.S)
    if not mo or not mp:
        raise SystemExit("no portal tables in %s_spawn.h" % prefix)
    ofs = [int(v) for v in re.findall(r'-?\d+', mo.group(1))]
    rows = re.findall(r'\{([^}]*)\}', mp.group(1))
    out = []
    for r in range(len(ofs) - 1):
        for i in range(ofs[r], ofs[r + 1]):
            v = [int(x) for x in re.findall(r'-?\d+', rows[i])]
            pts = [(v[1 + k * 3], v[2 + k * 3], v[3 + k * 3]) for k in range(4)]
            out.append((r, v[0], [p[0] for p in pts], [p[1] for p in pts], [p[2] for p in pts]))
    return out


def main():
    pfx = sys.argv[sys.argv.index("--prefix") + 1] if "--prefix" in sys.argv else "mrt"
    patch = "--patch" in sys.argv
    ipath = _disc(os.path.join(D, pfx + ".bin"))
    spath = _disc(os.path.join(D, pfx + "_sect.bin"))
    idx = open(ipath, "rb").read()
    sect = bytearray(open(spath, "rb").read())
    nroom = struct.unpack_from(">H", idx, 0)[0]

    meta = []
    for r in range(nroom):
        _, soff = struct.unpack_from(">II", idx, 8 + r * 8)
        soff &= 0x7FFFFFFF
        xS, zS = struct.unpack_from(">HH", sect, soff)
        ix, iz = struct.unpack_from(">ii", sect, soff + 4)
        meta.append((soff, xS, zS, ix, iz))

    def cell_off(r, cx, cz):
        soff, xS, zS, ix, iz = meta[r]
        return soff + 12 + (cx * zS + cz) * 6

    def opened(r, cx, cz):
        soff, xS, zS, ix, iz = meta[r]
        if not (0 <= cx < xS and 0 <= cz < zS):
            return 0
        o = cell_off(r, cx, cz)
        if struct.unpack_from(">H", sect, o)[0] != WALL:
            return 0                      # floor or already open - never touch
        struct.pack_into(">H", sect, o, OPEN)
        return 1

    total = 0
    per_room = {}
    for (r, dst, xs, ys, zs) in portals(pfx):
        soff, xS, zS, ix, iz = meta[r]
        x0, x1, z0, z1 = min(xs), max(xs), min(zs), max(zs)
        n = 0
        if z0 == z1:                       # a Z-PLANE: separates two cell ROWS
            czb = (z0 - iz) // CELL        # row starting at the plane
            for cx in range((x0 - ix) // CELL, (x1 - ix + CELL - 1) // CELL):
                n += opened(r, cx, czb) + opened(r, cx, czb - 1)
        elif x0 == x1:                     # an X-PLANE: separates two cell COLUMNS
            cxb = (x0 - ix) // CELL
            for cz in range((z0 - iz) // CELL, (z1 - iz + CELL - 1) // CELL):
                n += opened(r, cxb, cz) + opened(r, cxb - 1, cz)
        else:                              # not axis-aligned - open every cell it spans
            for cx in range((x0 - ix) // CELL, (x1 - ix + CELL - 1) // CELL):
                for cz in range((z0 - iz) // CELL, (z1 - iz + CELL - 1) // CELL):
                    n += opened(r, cx, cz)
        if n:
            per_room[r] = per_room.get(r, 0) + n
        total += n

    # ☠️ --audit: is every DOORWAY actually passable? A room with openings can
    # still have a dead door, and "rooms with zero openings" is a WEAK metric - it
    # called gym room 18 sealed when room 18 is the POOL, a water volume under a
    # surface (room 14's cells over it read floor 3585: bit 0 is the extractor's
    # WATER-SURFACE mark, main.c `w = fy & 1`). A vertical portal needs no
    # horizontal opening at all.
    # So check the thing that matters: for each portal, does EACH side have a
    # passable cell touching the plane? Passable = a real floor or 0x7FFE.
    if "--audit" in sys.argv:
        def passable(r, cx, cz):
            soff, xS, zS, ix, iz = meta[r]
            if not (0 <= cx < xS and 0 <= cz < zS):
                return False
            return struct.unpack_from(">H", sect, cell_off(r, cx, cz))[0] != WALL

        bad = 0
        for (r, dst, xs, ys, zs) in portals(pfx):
            x0, x1, y0, y1, z0, z1 = min(xs), max(xs), min(ys), max(ys), min(zs), max(zs)
            if y0 == y1 and x0 != x1 and z0 != z1:
                continue                      # HORIZONTAL plane = vertical portal
            sides = []
            for who in (r, dst):
                soff, xS, zS, ix, iz = meta[who]
                ok = False
                if z0 == z1:
                    cz = (z0 - iz) // CELL
                    for cx in range((x0 - ix) // CELL, (x1 - ix + CELL - 1) // CELL):
                        ok = ok or passable(who, cx, cz) or passable(who, cx, cz - 1)
                elif x0 == x1:
                    cx = (x0 - ix) // CELL
                    for cz in range((z0 - iz) // CELL, (z1 - iz + CELL - 1) // CELL):
                        ok = ok or passable(who, cx, cz) or passable(who, cx - 1, cz)
                sides.append(ok)
            if not all(sides):
                bad += 1
                print("  ☠️ DEAD DOOR %d -> %d  (passable: %s side %s, %s side %s)"
                      % (r, dst, r, sides[0], dst, sides[1]))
        print("%s: %d dead doors out of %d wall-portals"
              % (pfx, bad, sum(1 for (r, d, xs, ys, zs) in portals(pfx)
                               if not (min(ys) == max(ys) and min(xs) != max(xs) and min(zs) != max(zs)))))
        return

    sealed = []
    for r in range(nroom):
        soff, xS, zS, ix, iz = meta[r]
        if not any(struct.unpack_from(">H", sect, cell_off(r, c // zS, c % zS))[0] == OPEN
                   for c in range(xS * zS)):
            sealed.append(r)

    print("%s: %d cells opened across %d rooms" % (pfx, total, len(per_room)))
    print("  rooms still with ZERO openings: %d %s" % (len(sealed), sealed))
    if patch:
        open(spath, "wb").write(bytes(sect))
        print("  PATCHED %s" % os.path.basename(spath))
    else:
        print("  (dry run - pass --patch to write)")


if __name__ == "__main__":
    main()
