#!/usr/bin/env python3
# tr2jag_sound.py — extract + decode TR1 PSX sound samples (SPU ADPCM) into
# a Jaguar SFX bank: 8-bit signed PCM, native 11025Hz, LONG-ALIGNED (Jerry
# reads DRAM as longs only).
#
# sfx.bin (big-endian):
#   u16 count, u16 pad
#   count * { u32 off, u32 len }      (byte offset from blob start, len)
#   pcm bytes... (each sample 4-aligned, s8 PCM)
# sfx.h: #define SFX_<NAME> slot indices
import struct, sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

LEVEL=os.environ.get("TRLEVEL", os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "assets/extracted/PSXDATA/LEVEL1.PSX"))
OUT  = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# TR1 sound EVENT ids -> our slot names (sample chosen via soundMap+SoundInfo)
# (event, name, max_seconds or 0) — pistol/splash return with guns/water
# NOTE: event 30 = SND_SCREAM (falling death) — it was mislabeled GRUNT and
# played on climbs (user-reported 2026-07-13). Event 31 = SND_HIT, Lara's
# short "uh!" — the right effort vocal (TR1 climbs carry no anim-command
# sound of their own; verified against the PSX anim command stream).
WANTED = [ (0,"STEP",0), (4,"LAND",0), (31,"GRUNT",0.8),
           (108,"MENU_SPIN",0), (111,"MENU_SHOW",0), (112,"MENU_HIDE",0) ]

raw=open(LEVEL,'rb').read()
# --- sound offsets/data (loadTR1_PSX fixed layout) ---
numSounds,=struct.unpack_from("<H",raw,22)
p=2086+numSounds*512
offs=[]; sizes=[]; total=0
for i in range(numSounds):
    sz,=struct.unpack_from("<H",raw,p); p+=2
    offs.append(total); sizes.append(sz*8); total+=sz*8
sndData=2600+numSounds*512
print("samples:",numSounds,"total ADPCM bytes:",total)

# --- SPU ADPCM decode ---
F=[(0,0),(60,0),(115,-52),(98,-55),(122,-60)]
def spu_decode(off,length):
    out=[]; h1=h2=0
    end=off+length
    while off+16<=end:
        blk=raw[off:off+16]; off+=16
        shift=blk[0]&0xF; filt=(blk[0]>>4)&0xF
        flags=blk[1]
        if filt>4: filt=0
        f0,f1=F[filt]
        for n in range(28):
            b=blk[2+n//2]
            nib=(b&0xF) if (n&1)==0 else (b>>4)
            s=nib<<12
            if s&0x8000: s-=0x10000
            s>>= shift
            s += (h1*f0 + h2*f1) >> 6
            s=max(-32768,min(32767,s))
            h2=h1; h1=s
            out.append(s)
        if flags&1: break   # end flag
    return out

# --- locate soundMap by SCAN (the PSX walk strides vary; the map is a
# distinctive 256*int16 run of values in [-1..numSounds+small]) ---
def find_soundmap():
    best=None
    for off in range(2600, len(raw)-512-8, 2):
        ok=True; nonneg=0; asc=0; prev=-2
        for i in range(256):
            v,=struct.unpack_from("<h",raw,off+i*2)
            if v<-1 or v>numSounds+8: ok=False; break
            if v>=0:
                nonneg+=1
                if v==prev+1: asc+=1
                prev=v
        if ok and 20<nonneg<220 and asc>nonneg//2:
            # validate: mapped SoundInfos must have sane sample offsets
            pS=off+512; good=0; tot=0
            for i in range(256):
                v,=struct.unpack_from("<h",raw,off+i*2)
                if v<0: continue
                tot+=1
                if pS+v*8+6<=len(raw):
                    so,=struct.unpack_from("<H",raw,pS+v*8+4)  # PSX: sample idx at +4
                    if 0<so<numSounds: good+=1
            if tot and good>tot*3//4:
                best=off; break
    return best
smOff=find_soundmap()
assert smOff is not None, "soundMap not found"
soundMap=[struct.unpack_from("<h",raw,smOff+i*2)[0] for i in range(256)]
pSI=smOff+512
si_n=(len(raw)-pSI)//8
print("soundMap @%d, ~%d SoundInfos"%(smOff,si_n))
def sample_for_event(ev):
    m=soundMap[ev]
    if m<0 or m>=si_n: return -1
    idx,=struct.unpack_from("<H",raw,pSI+m*8+4) # PSX SoundInfo: sample idx at +4
    return idx if idx<numSounds else -1

blob_pcm=bytearray(); recs=[]; names=[]
for ev,name,maxs in WANTED:
    sidx=sample_for_event(ev)
    if sidx<0:
        print("event %d (%s): unmapped, skipped"%(ev,name)); continue
    pcm=spu_decode(sndData+offs[sidx], sizes[sidx])
    if maxs and len(pcm)>int(maxs*11025):
        cut=int(maxs*11025); fade=min(1024,cut)
        pcm=pcm[:cut]
        for k in range(fade):    # fade the tail so the cut doesn't click
            pcm[cut-fade+k]=pcm[cut-fade+k]*(fade-k)//fade
    while len(blob_pcm)&3: blob_pcm+=b'\0'
    o=len(blob_pcm)
    blob_pcm+=bytes(((s>>8)&0xFF) for s in pcm)
    recs.append((o,len(pcm))); names.append(name)
    print("event %3d %-10s sample %3d: %5d pcm (%.2fs @11kHz)"%(ev,name,sidx,len(pcm),len(pcm)/11025.0))

hdr=struct.pack(">HH",len(recs),0)
for (o,l) in recs: hdr+=struct.pack(">II",o+4+len(recs)*8,l)
open(os.path.join(OUT,'sfx.bin'),'wb').write(hdr+bytes(blob_pcm))
with open(os.path.join(OUT,'sfx.h'),'w') as f:
    f.write("/* generated by tr2jag_sound.py */\n")
    for i,nm in enumerate(names): f.write("#define SFX_%s %d\n"%(nm,i))
    f.write("#define SFX_COUNT %d\n"%len(recs))
print("sfx.bin %d bytes"%(len(hdr)+len(blob_pcm)))
